export const coffees = [
  {
    id: 1,
    photo: 'Type=Expresso.svg',
    tags: ['TRADICIONAL'],
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
  },
  {
    id: 2,
    photo: 'Type=Americano.svg',
    tags: ['TRADICIONAL'],
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.9,
  },
  {
    id: 3,
    photo: 'Type=Expresso Cremoso.svg',
    tags: ['TRADICIONAL'],
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 9.9,
  },
  {
    id: 4,
    photo: 'Type=Café Gelado.svg',
    tags: ['TRADICIONAL', 'GELADO'],
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café e cubos de gelo',
    price: 9.9,
  },
  {
    id: 5,
    photo: 'Type=Café com Leite.svg',
    tags: ['TRADICIONAL', 'COM LEITE'],
    name: 'Café com Leite',
    description:
      'Meio a meio de café expresso tradicional com leite vaporizado',
    price: 9.9,
  },
  {
    id: 6,
    photo: 'Type=Latte.svg',
    tags: ['TRADICIONAL', 'COM LEITE'],
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e uma espuma cremosa',
    price: 9.9,
  },
  {
    id: 7,
    photo: 'Type=Capuccino.svg',
    tags: ['TRADICIONAL', 'COM LEITE'],
    name: 'Capuccino',
    description:
      'Bebia com canela feita de doses iguais de café, leite e espuma',
    price: 9.9,
  },
  {
    id: 8,
    photo: 'Type=Macchiato.svg',
    tags: ['TRADICIONAL', 'COM LEITE'],
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.9,
  },
  {
    id: 9,
    photo: 'Type=Mochaccino.svg',
    tags: ['TRADICIONAL', 'COM LEITE'],
    name: 'Mocaccino',
    description:
      'Café expresso com uma calda de chocolate, pouco leite e espuma',
    price: 9.9,
  },
  {
    id: 10,
    photo: 'Type=Chocolate Quente.svg',
    tags: ['ESPECIAL', 'COM LEITE'],
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.9,
  },
  {
    id: 11,
    photo: 'Type=Cubano.svg',
    tags: ['ESPECIAL', 'ALCOÓLIGO', 'GELADO'],
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.9,
  },
  {
    id: 12,
    photo: 'Type=Havaiano.svg',
    tags: ['ESPECIAL'],
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de côco',
    price: 9.9,
  },
  {
    id: 13,
    photo: 'Type=Árabe.svg',
    tags: ['ESPECIAL'],
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.9,
  },
  {
    id: 14,
    photo: 'Type=Irlandês.svg',
    tags: ['ESPECIAL', 'ALCOÓLICO'],
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.9,
  },
]
